Repository nkc-cta20-team3/N-suma, pull requests merged in 2023-06, with the labels that each got.

#70 69-POST用コード記述
  go/src/main/api/UnAuthorizationList.go
  go/src/main/model/absence.go
Labels: Backend

#74 71-POSTでUnAuthorizationList
  go/src/main/api/UnAuthorizationList.go
  go/src/main/api/UnAuthorizationListGet.go
  go/src/main/main.go
  go/src/main/model/absence.go
  vue/app/N-suma/src/router/index.js
  vue/app/N-suma/src/views/test.vue
Labels: Backend, Frontend

#79 78 gas cicd
  .github/workflows/GoogleAppScript-merge.yml
  gas/appsscript.json
  gas/sendtoAPI.js
Labels: aws

#85 75-未認可リストAPI修正
  go/src/main/api/UnAuthorizationList.go
  go/src/main/api/UnAuthorizationListGet.go
  go/src/main/model/absence.go
Labels: Backend

#88 86-公欠届認可機能実装
  go/src/main/api/UpdateAuth.go
  go/src/main/main.go
  go/src/main/model/absence.go
Labels: Backend

#93 54 status store
  go/src/main/api/UpdateAuth.go
  go/src/main/model/absence.go
  vue/app/N-suma/package.json
  vue/app/N-suma/src/main.js
  vue/app/N-suma/src/store/index.js
  vue/app/N-suma/src/views/document_accept.vue
  vue/app/N-suma/src/views/document_auth.vue
  vue/app/N-suma/yarn.lock
Labels: Frontend

#98 absence update
  go/src/main/api/AbsenceDocuments.go
  go/src/main/api/AuthorizeAbsence.go
  go/src/main/api/DeleteAbsence.go
  go/src/main/api/ReadAuthList.go
  go/src/main/api/ReadDocument.go
  go/src/main/api/RegisterAbsence.go
  go/src/main/api/UnAuthorizationList.go
  go/src/main/api/UpdateAuth.go
  go/src/main/main.go
  go/src/main/model/absence.go
  vue/app/N-suma/package.json
  vue/app/N-suma/src/main.js
  vue/app/N-suma/src/store/index.js
  vue/app/N-suma/src/views/document_accept.vue
  vue/app/N-suma/src/views/document_auth.vue
  vue/app/N-suma/yarn.lock
Labels: Backend, Frontend, most important
